#! /bin/bash

if [[ "$(hostname)" == "mblin" ]] ; then
    bspc monitor DP-0 -d 一 二 三 四 五
    bspc monitor DP-2 -d 六 七 八 九 十
    bspc monitor DP-4 -d 十一 十二 十三 十四 十五
else
    bspc monitor -d 一 二 三 四 五 六 七 八 九 十
fi

bspc config border_width          2
bspc config window_gap            12
bspc config focus_follows_pointer false

source $HOME/.cache/wal/colors.sh
bspc config focused_border_color  "$color2"
bspc config active_border_color   "$color0"
bspc config presel_feedback_color "$color1"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Load local rules
$HOME/.config/bspwm/rules-${HOSTNAME}.sh

# Load local autostarts
$HOME/.config/bspwm/autostart-${HOSTNAME}.sh

# Load local wallpaper
$HOME/.config/bspwm/wallpaper-${HOSTNAME}.sh &
