#! /bin/bash

if [[ "$(hostname)" == "mblin" ]] ; then
    bspc monitor DP-0 -d 1 2 3 4 5
    bspc monitor DP-2 -d 6 7 8 9 0
    bspc monitor DP-4 -d 11 12 13 14 15
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width          2
bspc config window_gap            12
bspc config focus_follows_pointer false

source $HOME/.cache/wal/colors.sh
bspc config focused_border_color  "$color2"
bspc config active_border_color   "$color0"
bspc config presel_feedback_color "$color1"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Load local rules
$HOME/.config/bspwm/rules-${HOSTNAME}.sh

# Load local autostarts
$HOME/.config/bspwm/autostart-${HOSTNAME}.sh

# Load local wallpaper
$HOME/.config/bspwm/wallpaper-${HOSTNAME}.sh &
